### ----------------------------------------------------
### Content of this script is generated by TILESGenerator.gd (TSUpdate)
### ----------------------------------------------------

extends Node

### TILESET TILE NAMES START ###
enum ENVIROMENT {WoodenPlankWalls_GEN_ = 0, StoneWalls_GEN_ = 1, SteelWalls_GEN_ = 2, DirtWalls_GEN_ = 3, GrassWalls_GEN_ = 4, DarkGrassWalls_GEN_ = 5, PineTree = 6, LeafTree = 7, Bush = 8, Grass = 9, Pebble = 10, }
enum FLOOR {WoodenPlankFloor_GEN_ = 0, StoneFloor_GEN_ = 1, SteelFloor_GEN_ = 2, DirtFloor_GEN_ = 3, GrassFloor_GEN_ = 4, DarkGrassFloor_GEN_ = 5, }
### TILESET TILE NAMES END ###
