### ----------------------------------------------------
### Content of this script is generated by SetupTiles.gd (Dev Tool)
### ----------------------------------------------------
tool
extends TileSet

### BINDS DICT START
const BINDS = {
0: [ 0, 1, 2, 3, 4, 5, 12, 13 ],
1: [ 0, 1, 2, 3, 4, 5, 12, 13 ],
2: [ 0, 1, 2, 3, 4, 5, 12, 13 ],
3: [ 0, 1, 2, 3, 4, 5, 12, 13 ],
4: [ 0, 1, 2, 3, 4, 5, 12, 13 ],
5: [ 0, 1, 2, 3, 4, 5, 12, 13 ],
12: [ 0, 1, 2, 3, 4, 5, 12, 13 ],
13: [ 0, 1, 2, 3, 4, 5, 12, 13 ]
}
### BINDS DICT END
func _is_tile_bound(drawn_id, neighbor_id):
	if drawn_id in BINDS:
		return neighbor_id in BINDS[drawn_id]
	return false