### ----------------------------------------------------
### Content of this script is generated by SetupTiles.gd (Dev Tool)
### ----------------------------------------------------
tool
extends TileSet

### BINDS DICT START
const BINDS = {
5: [ 5, 6, 7, 8, 9, 10 ],
6: [ 5, 6, 7, 8, 9, 10 ],
7: [ 5, 6, 7, 8, 9, 10 ],
8: [ 5, 6, 7, 8, 9, 10 ],
9: [ 5, 6, 7, 8, 9, 10 ],
10: [ 5, 6, 7, 8, 9, 10 ]
}
### BINDS DICT END
func _is_tile_bound(drawn_id, neighbor_id):
	if drawn_id in BINDS:
		return neighbor_id in BINDS[drawn_id]
	return false