### ----------------------------------------------------
### Content of this script is generated by ScriptsGenerator.gd (addons/UpdateTileMaps)
### ----------------------------------------------------

tool
extends TileSet

### BINDS DICT START ###
const BINDS = {
}
### BINDS DICT END ###
func _is_tile_bound(drawn_id, neighbor_id):
	if drawn_id in BINDS:
		return neighbor_id in BINDS[drawn_id]
	return false